#!/bin/bash
tour_directories()
{
    dir=$(dir -1)
    dir=$(echo ${dir:6})
    for file in $dir;
    do
      # we confirm if the file is empty
      if [ -n $file ]; then
        if [ -d "$file" ]; then
            # if is a directory, we enter there, 
            # call recursively to the function tour_directories
            echo "DIR: " $file
            cd $file
            tour_directories ./
            # when we finish to use it we close it
            cd ..
        else
            # the extension is divided with the file name and displayed on the screen
            extension=${file##*.}
            path_and_name=${file%.*}
            echo "File: "$path_and_name.$extension
            #chmod 644 $file
        fi;
      fi;
     done;
}
